ex06bundle_index:
    path: /ex06
    controller: App\Ex06Bundle\Controller\Ex06Controller::index

ex06_create_table:
    path: /ex06/create
    controller: App\Ex06Bundle\Controller\Ex06Controller::createDataInTable

ex06_select:
    path: /ex06/select
    controller: App\Ex06Bundle\Controller\Ex06Controller::selectTableContent

ex06_update_data:
    path: /ex06/update/{id}
    controller: App\Ex06Bundle\Controller\Ex06Controller::updateTableContent