<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTm8x5tx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTm8x5tx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTm8x5tx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTm8x5tx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTm8x5tx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tm8x5tx',
    'container.build_id' => '18d5e831',
    'container.build_time' => 1748632892,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTm8x5tx');
