security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            stateless: false
            custom_authenticator: App\Security\UserCustomAuthenticator
            logout:
                path: app_logout
                target: e04_index
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        - { path: ^/e04/welcome, roles: ROLE_USER }
        - { path: ^/e04/post, roles: ROLE_USER }
        - { path: ^/e04, roles: IS_AUTHENTICATED_ANONYMOUSLY }
