<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXLfUrcl\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXLfUrcl/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXLfUrcl.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXLfUrcl\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXLfUrcl\App_KernelProdContainer([
    'container.build_hash' => 'XLfUrcl',
    'container.build_id' => '57e74c35',
    'container.build_time' => 1749235015,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXLfUrcl');
