ex03_index:
    path: /ex03
    controller: App\Ex03Bundle\Controller\Ex03Controller::index

ex03_insert:
    path: /ex03/insert
    controller: App\Ex03Bundle\Controller\Ex03Controller::insert

ex03_select:
    path: /ex03/select
    controller: App\Ex03Bundle\Controller\Ex03Controller::select

ex03_delete:
    path: /ex03/delete
    controller: App\Ex03Bundle\Controller\Ex03Controller::delete