<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXmWvJon\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXmWvJon/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXmWvJon.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXmWvJon\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXmWvJon\App_KernelDevDebugContainer([
    'container.build_hash' => 'XmWvJon',
    'container.build_id' => 'cd9ea5cf',
    'container.build_time' => 1744638831,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXmWvJon');
