<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZlwpykb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZlwpykb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZlwpykb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZlwpykb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZlwpykb\App_KernelDevDebugContainer([
    'container.build_hash' => 'Zlwpykb',
    'container.build_id' => 'baacf6ff',
    'container.build_time' => 1749234071,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZlwpykb');
