<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOkhBc6n\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOkhBc6n/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOkhBc6n.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOkhBc6n\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOkhBc6n\App_KernelDevDebugContainer([
    'container.build_hash' => 'OkhBc6n',
    'container.build_id' => '582f8f89',
    'container.build_time' => 1744649261,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOkhBc6n');
