<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS6gfXZ1\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS6gfXZ1/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerS6gfXZ1.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerS6gfXZ1\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerS6gfXZ1\App_KernelProdContainer([
    'container.build_hash' => 'S6gfXZ1',
    'container.build_id' => 'fe2ad104',
    'container.build_time' => 1749921046,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS6gfXZ1');
