<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'ex03_index' => [[], ['_controller' => 'App\\Ex03Bundle\\Controller\\Ex03Controller::index'], [], [['text', '/ex03']], [], [], []],
    'ex03_insert' => [[], ['_controller' => 'App\\Ex03Bundle\\Controller\\Ex03Controller::insert'], [], [['text', '/ex03/insert']], [], [], []],
    'ex03_select' => [[], ['_controller' => 'App\\Ex03Bundle\\Controller\\Ex03Controller::select'], [], [['text', '/ex03/select']], [], [], []],
    'ex03_delete' => [[], ['_controller' => 'App\\Ex03Bundle\\Controller\\Ex03Controller::delete'], [], [['text', '/ex03/delete']], [], [], []],
    'App\Ex03Bundle\Controller\Ex03Controller::index' => [[], ['_controller' => 'App\\Ex03Bundle\\Controller\\Ex03Controller::index'], [], [['text', '/ex03']], [], [], []],
    'App\Ex03Bundle\Controller\Ex03Controller::insert' => [[], ['_controller' => 'App\\Ex03Bundle\\Controller\\Ex03Controller::insert'], [], [['text', '/ex03/insert']], [], [], []],
    'App\Ex03Bundle\Controller\Ex03Controller::select' => [[], ['_controller' => 'App\\Ex03Bundle\\Controller\\Ex03Controller::select'], [], [['text', '/ex03/select']], [], [], []],
    'App\Ex03Bundle\Controller\Ex03Controller::delete' => [[], ['_controller' => 'App\\Ex03Bundle\\Controller\\Ex03Controller::delete'], [], [['text', '/ex03/delete']], [], [], []],
];
