parameters:

services:
    App\Validator\EmployeeBusinessValidator:
        arguments:
            $em: '@doctrine.orm.entity_manager'
        tags: ['validator.constraint_validator']

    App\Ex13Bundle\Controller\Ex13Controller:
        calls:
            - setContainer: [ '@service_container' ]
        tags: ['controller.service_arguments']
        public: true
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'





