ex01_index:
    path: /ex01
    controller: App\Ex01Bundle\Controller\Ex01Controller::index

ex01_create_table:
    path: /ex01/create
    controller: App\Ex01Bundle\Controller\Ex01Controller::createTable

ex01_delete_table:
    path: /ex01/delete
    controller: App\Ex01Bundle\Controller\Ex01Controller::deleteTable