ex08_index:
    path: /ex08
    controller: App\Ex08Bundle\Controller\Ex08Controller::index

ex08_create_persons:
    path: /ex08/create-persons
    controller: App\Ex08Bundle\Controller\Ex08Controller::createPersonsTable

ex08_add_marital_status:
    path: /ex08/add-marital-status
    controller: App\Ex08Bundle\Controller\Ex08Controller::addMaritalStatusColumn

ex08_create_address_tables:
    path: /ex08/create-address-table
    controller: App\Ex08Bundle\Controller\Ex08Controller::createAddressesTable

ex08_create_bankaccount_tables:
    path: /ex08/create-bankaccount-table
    controller: App\Ex08Bundle\Controller\Ex08Controller::createBankAccountsTable

ex08_add_Addresses:
    path: /ex08/add-relations-addresses
    controller: App\Ex08Bundle\Controller\Ex08Controller::addRelationsAddresses

ex08_add_bankAccount:
    path: /ex08/add-relations-BankAccount
    controller: App\Ex08Bundle\Controller\Ex08Controller::addRelationsBankAccount

ex08_drop_tables:
    path: /ex08/drop-tables
    controller: App\Ex08Bundle\Controller\Ex08Controller::dropTables
