<?php

namespace ContainerXLfUrcl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Ex00Bundle\\Controller\\Ex00Controller::createTable' => ['privates', '.service_locator.hUbu2Ln', 'get_ServiceLocator_HUbu2LnService', true],
            'App\\Ex00Bundle\\Controller\\Ex00Controller::deleteTable' => ['privates', '.service_locator.hUbu2Ln', 'get_ServiceLocator_HUbu2LnService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Ex00Bundle\\Controller\\Ex00Controller:createTable' => ['privates', '.service_locator.hUbu2Ln', 'get_ServiceLocator_HUbu2LnService', true],
            'App\\Ex00Bundle\\Controller\\Ex00Controller:deleteTable' => ['privates', '.service_locator.hUbu2Ln', 'get_ServiceLocator_HUbu2LnService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Ex00Bundle\\Controller\\Ex00Controller::createTable' => '?',
            'App\\Ex00Bundle\\Controller\\Ex00Controller::deleteTable' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Ex00Bundle\\Controller\\Ex00Controller:createTable' => '?',
            'App\\Ex00Bundle\\Controller\\Ex00Controller:deleteTable' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));
    }
}
