<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQJtNte8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQJtNte8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQJtNte8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQJtNte8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQJtNte8\App_KernelDevDebugContainer([
    'container.build_hash' => 'QJtNte8',
    'container.build_id' => '8f824655',
    'container.build_time' => 1745155739,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQJtNte8');
