<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXGdCSLx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXGdCSLx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXGdCSLx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXGdCSLx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXGdCSLx\App_KernelDevDebugContainer([
    'container.build_hash' => 'XGdCSLx',
    'container.build_id' => 'd6f95bab',
    'container.build_time' => 1745157649,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXGdCSLx');
