<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJG82Yks\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJG82Yks/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJG82Yks.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJG82Yks\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJG82Yks\App_KernelDevDebugContainer([
    'container.build_hash' => 'JG82Yks',
    'container.build_id' => '33b6257b',
    'container.build_time' => 1749236165,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJG82Yks');
