<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'ex01bundle_index' => [[], ['_controller' => 'App\\Ex01Bundle\\Controller\\Ex01Controller::index'], [], [['text', '/ex01']], [], [], []],
    'App\Ex01Bundle\Controller\Ex01Controller::index' => [[], ['_controller' => 'App\\Ex01Bundle\\Controller\\Ex01Controller::index'], [], [['text', '/ex01']], [], [], []],
];
