<?php

namespace ContainerS6gfXZ1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Ex03Bundle\Service\UserService' shared autowired service.
     *
     * @return \App\Ex03Bundle\Service\UserService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Ex03Bundle\\Service\\UserService'] = new \App\Ex03Bundle\Service\UserService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
