<?php

namespace ContainerTm8x5tx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zyq1BTiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zyq1BTi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zyq1BTi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userManager' => ['privates', 'App\\Ex03Bundle\\Service\\UserService', 'getUserServiceService', true],
        ], [
            'userManager' => 'App\\Ex03Bundle\\Service\\UserService',
        ]);
    }
}
