<?php

namespace ContainerTm8x5tx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SRUFz1nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SRUFz1n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SRUFz1n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Ex03Bundle\\Controller\\Ex03Controller::insert' => ['privates', '.service_locator.zyq1BTi', 'get_ServiceLocator_Zyq1BTiService', true],
            'App\\Ex03Bundle\\Controller\\Ex03Controller::select' => ['privates', '.service_locator.zyq1BTi', 'get_ServiceLocator_Zyq1BTiService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Ex03Bundle\\Controller\\Ex03Controller:insert' => ['privates', '.service_locator.zyq1BTi', 'get_ServiceLocator_Zyq1BTiService', true],
            'App\\Ex03Bundle\\Controller\\Ex03Controller:select' => ['privates', '.service_locator.zyq1BTi', 'get_ServiceLocator_Zyq1BTiService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Ex03Bundle\\Controller\\Ex03Controller::insert' => '?',
            'App\\Ex03Bundle\\Controller\\Ex03Controller::select' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Ex03Bundle\\Controller\\Ex03Controller:insert' => '?',
            'App\\Ex03Bundle\\Controller\\Ex03Controller:select' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
