<?php

namespace Container1LGtZTo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__9MMiQQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..9MMiQQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..9MMiQQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'connection' => ['services', 'doctrine.dbal.default_connection', 'getDoctrine_Dbal_DefaultConnectionService', true],
            'request' => ['privates', '.errored.pYuDA09', NULL, 'Cannot determine controller argument for "App\\Ex00Bundle\\Controller\\Ex00Controller::index()": the $request argument is type-hinted with the non-existent class or interface: "App\\Ex00Bundle\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'connection' => '?',
            'request' => '?',
        ]);
    }
}
