<?php

namespace Container1LGtZTo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_PYuDA09Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.pYuDA09' shared service.
     *
     * @return \App\Ex00Bundle\Controller\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Ex00Bundle\\Controller\\Ex00Controller::index()": the $request argument is type-hinted with the non-existent class or interface: "App\\Ex00Bundle\\Controller\\Request". Did you forget to add a use statement?');
    }
}
