<?php

namespace ContainerBM2DUgB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_FFCg10LService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.fFCg10L' shared service.
     *
     * @return \App\Service\UserService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Ex03Bundle\\Controller\\Ex03Controller::select()": the $userManager argument is type-hinted with the non-existent class or interface: "App\\Service\\UserService".');
    }
}
