<?php

namespace ContainerBM2DUgB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FRTiDOYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FRTiDOY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FRTiDOY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userManager' => ['privates', '.errored.fFCg10L', NULL, 'Cannot determine controller argument for "App\\Ex03Bundle\\Controller\\Ex03Controller::select()": the $userManager argument is type-hinted with the non-existent class or interface: "App\\Service\\UserService".'],
        ], [
            'userManager' => '?',
        ]);
    }
}
